### ISSUE TITLE
Version 1.4 implicitly depends on R>= 3.4

### ISSUE THREAD

**Issue by hsloot** [GeoBosh/rbibutils#1]
Your call to `R_unif_index`  in 

https://github.com/GeoBosh/rbibutils/blob/8476b2e9e4d662acf2bf8e3971f885efb6921ef3/src/intlist.c#L419

leads to `undefined symbol: R_unif_index` error since this function is only defined in R 3.4 and publicly introduced as API in R 3.5. In my case, this causes the CI of my package (which depend on Rdpack for creating the documentation) on R 3.3 to fail. This will also cause problems for all package developers that use the Github action workflow in https://github.com/r-lib/actions/blob/master/examples/check-full.yaml for their CI which tests on R 3.3.

You could use the following workaround: 

```c
#include <Rversion.h> 
// ...
#if defined(R_VERSION) && R_VERSION >= R_Version(3, 4, 0)
  return floor + ( (int) R_unif_index((double) RAND_MAX)) ) % len;
#else
  return  floor + ( (int) floor(RAND_MAX * unif_rand()) ) % len;
#endif
```

Note that your solution and my workaround will probably be biased (see section 3 in https://isocpp.org/files/papers/n3551.pdf). A better solution might be the following which should produce random integers in [floor, floor+len) and is consistent with R's way to sample a random integer on R< 3.4 and R >= 3.4:

```c
#include <Rversion.h> 
// ...
#if defined(R_VERSION) && R_VERSION >= R_Version(3, 4, 0)
  return floor + ( (int) R_unif_index((double) len)) );
#else
  return  floor + ( (int) floor(len * unif_rand()) );
#endif
```

**Comment by GeoBosh** [comment]
Thanks for the detailed report and the fix. The code has actually not changed since the first release of `rbibutils`. Although I followed on R-devel the discussion on the biasedness of the old integer RNG in R, I opted for more mechanical replacement back then.


I adopted your second fix and uploaded the revision. Is it possible to test on github (I do not use github's workflow)? I test the reverse dependencies of Rdpack with every change in rbibutils, but only for the current and development versions of R.

**Comment by hsloot** [comment]
Happy to help. I do not think ad-hoc testing on Github is possible, but including a workflow for CI testing on Github (e.g. on every push and pull request to master) is not that complicated. Instructions can be found here: https://github.com/r-lib/actions. I forked your repo and included a simple workflow, see https://github.com/hsloot/rbibutils. 

While doing that I noticed that my code above has a bug (for R < 3.4), since the header `math.h` (required for the `floor` function) is missing and if it would be included, there would be a naming conflict with the argument `floor` and the function `floor`. So maybe one has to rename the arguments too. The code below fixes that and compiles with R 3.3.

```c
#include <math.h>
#include <Rversion.h>

// ...

/* Returns random integer in the range [lower,upper) */
static int
randomint( int lower, int upper )
{
	int len = upper - lower;
#if defined(R_VERSION) && R_VERSION >= R_Version(3, 4, 0)
	return lower + ( (int) R_unif_index((double) len));
#else
	return  lower + ( (int) floor(len * unif_rand()));
#endif
}
```

**Comment by GeoBosh** [comment]
Thanks, very comprehensive. Would you like to make a pull request and I will merge you fork.

**Comment by hsloot** [comment]
Sure. FYI: The action is based on https://github.com/r-lib/actions/blob/master/examples/check-standard.yaml with the extra line 

```yml
        - {os: ubuntu-20.04, r: '3.3', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
```

You should be able to upgrade this workflow in the future with `usethis::use_github_action_check_standard()` and adding an extra line for R 3.3 to test the conditional compilation. Also consider adding a badge to your README:

```
[![R build status](https://github.com/GeoBosh/rbibutils/workflows/R-CMD-check/badge.svg)](https://github.com/GeoBosh/rbibutils/actions)
```

**Comment by GeoBosh** [comment]
Very useful to have the workflow. I am using TravisCI in some packages but the native GitHub one looks like less hassle.
